package fr.whyt.pubg.main;

import fr.whyt.pubg.inout.ParserCIS;
import fr.whyt.pubg.inout.ParsingException;
import fr.whyt.pubg.inout.WriterCIS;
import fr.whyt.pubg.inout.cis.CustomInputSettings;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;

public class Main extends Application {

    public static Map<String, String> properties;

    static {
        properties = new HashMap<>();
        URL url = ClassLoader.getSystemResource("properties.config");
        //Object o = JSONFunctions.parse(url.getPath(), null);
    }

    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(ClassLoader.getSystemResource("main.fxml"));
        primaryStage.setTitle("Hello World");
        primaryStage.setScene(new Scene(root, 300, 275));
        primaryStage.show();

        try {
            CustomInputSettings cis = ParserCIS.serialize(source_line);
            //System.out.println(cis);
            String deserialize = WriterCIS.deserialize(cis);
            System.out.println(deserialize);
        } catch (ParsingException e) {
            e.printStackTrace();
            Parent exception = FXMLLoader.load(ClassLoader.getSystemResource("exception.fxml"));
        }
    }


    public static void main(String[] args) {
        launch(args);
    }
    
    /**
     * TEST: sources
     */
    public static String source_line = "CustomInputSettins=(ActionKeyList=((ActionName=\"Walk\",Keys=((Key=<),())),(ActionName=\"Sprint\",Keys=((Key=LeftShift),())),(ActionName=\"Jump\",Keys=((Key=SpaceBar),(),(Key=Gamepad_FaceButton_Bottom))),(ActionName=\"ToggleCrouch\",Keys=((Key=LeftControl),())),(ActionName=\"ToggleProne\",Keys=((Key=C),())),(ActionName=\"Interact\",Keys=((Key=F),(),(Key=Gamepad_FaceButton_Left))),(ActionName=\"ToggleCamera\",Keys=((Key=V),())),(ActionName=\"ToggleAutoRun\",Keys=((Key=Equals),(Key=NumLock))),(ActionName=\"HoldRotation\",Keys=((Key=LeftAlt),())),(ActionName=\"Fire\",Keys=((Key=LeftMouseButton),(),(Key=Gamepad_RightTrigger))),(ActionName=\"Targeting\",Keys=((Key=RightMouseButton),(),(Key=Gamepad_LeftTrigger))),(ActionName=\"Reload\",Keys=((Key=R),(),(Key=Gamepad_FaceButton_Top))),(ActionName=\"NextWeapon\",Keys=((Key=MouseScrollDown),())),(ActionName=\"PrevWeapon\",Keys=((Key=MouseScrollUp),())),(ActionName=\"Weapon_1\",Keys=((Key=Hyphen),())),(ActionName=\"Weapon_2\",Keys=((Key=E_AccentGrave),())),(ActionName=\"Weapon_3\",Keys=((Key=Underscore),())),(ActionName=\"Weapon_4\",Keys=((Key=C_Cedille),())),(ActionName=\"Weapon_5\",Keys=((Key=A_AccentGrave),())),(ActionName=\"ToggleFiringMode\",Keys=((Key=B),())),(ActionName=\"IncreaseZeroing\",Keys=((Key=ThumbMouseButton2),())),(ActionName=\"DecreaseZeroing\",Keys=((Key=ThumbMouseButton),())),(ActionName=\"PeekLeft\",Keys=((Key=A),())),(ActionName=\"PeekRight\",Keys=((Key=E),())),(ActionName=\"Unarm\",Keys=((Key=X),())),(ActionName=\"HoldBreath\",Keys=((Key=LeftShift),(),(Key=Gamepad_LeftShoulder))),(ActionName=\"UseGrenade\",Keys=((Key=G),())),(ActionName=\"UseFlashBang\",Keys=((Key=K),())),(ActionName=\"UseSmokeBomb\",Keys=((Key=H),())),(ActionName=\"UseMolotov\",Keys=((Key=J),())),(ActionName=\"ResetZeroing\",Keys=((Key=MiddleMouseButton),())),(ActionName=\"UseMedKit\",Keys=((Key=Ampersand),())),(ActionName=\"UseFirstAid\",Keys=((Key=E_AccentAigu),())),(ActionName=\"UseBandage\",Keys=((Key=Quote),())),(ActionName=\"UseBoostItem\",Keys=((Key=Apostrophe),())),(ActionName=\"UseHealItem\",Keys=((Key=Hyphen),())),(ActionName=\"UseAdrenaline\",Keys=(())),(ActionName=\"UsePainKiller\",Keys=(())),(ActionName=\"UseEnergyDrink\",Keys=(())),(ActionName=\"ToVehicleSeat_1\",Keys=((Key=NumPadOne),())),(ActionName=\"ToVehicleSeat_2\",Keys=((Key=NumPadTwo),())),(ActionName=\"ToVehicleSeat_3\",Keys=((Key=NumPadThree),())),(ActionName=\"ToVehicleSeat_4\",Keys=((Key=NumPadFour),())),(ActionName=\"ToVehicleSeat_5\",Keys=((Key=NumPadFive),())),(ActionName=\"Handbrake\",Keys=((Key=SpaceBar),(),(Key=Gamepad_FaceButton_Right))),(ActionName=\"VehicleBoost\",Keys=((Key=LeftShift),(),(Key=Gamepad_FaceButton_Bottom))),(ActionName=\"Horn\",Keys=((Key=LeftMouseButton),(),(Key=Gamepad_LeftThumbstick))),(ActionName=\"ToggleMap\",Keys=((Key=Comma),(),(Key=Gamepad_Special_Left))),(ActionName=\"ToggleInventory\",Keys=((Key=I),(Key=Tab))),(ActionName=\"ItemStackCountHandling\",Keys=((Key=LeftShift),())),(ActionName=\"ToggleUI\",Keys=((Key=U,bCtrl=True),())),(ActionName=\"DeleteMyMarker\",Keys=((Key=Delete),())),(ActionName=\"ToggleOption\",Keys=((Key=O),())),(ActionName=\"SetMapMarkerAtCurrentPosition\",Keys=((Key=Insert),())),(ActionName=\"PushToTalk\",Keys=((Key=T),())),(ActionName=\"ToggleMuteVoiceChat\",Keys=((Key=T,bCtrl=True),())),(ActionName=\"ToggleMuteMasterVolume\",Keys=((Key=M,bCtrl=True),())),(ActionName=\"SwitchVoiceChannel\",Keys=((Key=Y,bCtrl=True),())),(ActionName=\"PreviousPlayer\",Keys=((Key=End),())),(ActionName=\"NextPlayer\",Keys=((Key=Home),())),(ActionName=\"ObserverFastMove\",Keys=((Key=LeftShift),())),(ActionName=\"ObserverSlowMove\",Keys=((Key=LeftControl),())),(ActionName=\"ToggleObseverTagWidget\",Keys=((Key=H),())),(ActionName=\"ToggleShowObseverTagWeapon\",Keys=((Key=J),())),(ActionName=\"ToggleX-Ray\",Keys=((Key=X),())),(ActionName=\"ObserverSaveLocation0\",Keys=((Key=F10,bCtrl=True),())),(ActionName=\"ObserverSaveLocation1\",Keys=((Key=F1,bCtrl=True),())),(ActionName=\"ObserverSaveLocation2\",Keys=((Key=F2,bCtrl=True),())),(ActionName=\"ObserverSaveLocation3\",Keys=((Key=F3,bCtrl=True),())),(ActionName=\"ObserverSaveLocation4\",Keys=((Key=F4,bCtrl=True),())),(ActionName=\"ObserverSaveLocation5\",Keys=((Key=F5,bCtrl=True),())),(ActionName=\"ObserverSaveLocation6\",Keys=((Key=F6,bCtrl=True),())),(ActionName=\"ObserverSaveLocation7\",Keys=((Key=F7,bCtrl=True),())),(ActionName=\"ObserverSaveLocation8\",Keys=((Key=F8,bCtrl=True),())),(ActionName=\"ObserverSaveLocation9\",Keys=((Key=F9,bCtrl=True),())),(ActionName=\"ObserverSetLocation0\",Keys=((Key=F10),())),(ActionName=\"ObserverSetLocation1\",Keys=((Key=F1),())),(ActionName=\"ObserverSetLocation2\",Keys=((Key=F2),())),(ActionName=\"ObserverSetLocation3\",Keys=((Key=F3),())),(ActionName=\"ObserverSetLocation4\",Keys=((Key=F4),())),(ActionName=\"ObserverSetLocation5\",Keys=((Key=F5),())),(ActionName=\"ObserverSetLocation6\",Keys=((Key=F6),())),(ActionName=\"ObserverSetLocation7\",Keys=((Key=F7),())),(ActionName=\"ObserverSetLocation8\",Keys=((Key=F8),())),(ActionName=\"ObserverSetLocation9\",Keys=((Key=F9),())),(ActionName=\"ObserverSaveCharacter0\",Keys=((Key=Zero,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter1\",Keys=((Key=One,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter2\",Keys=((Key=Two,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter3\",Keys=((Key=Three,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter4\",Keys=((Key=Four,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter5\",Keys=((Key=Five,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter6\",Keys=((Key=Six,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter7\",Keys=((Key=Seven,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter8\",Keys=((Key=Eight,bCtrl=True),())),(ActionName=\"ObserverSaveCharacter9\",Keys=((Key=Nine,bCtrl=True),())),(ActionName=\"ObserverSetCharacterSpec0\",Keys=((Key=Zero),())),(ActionName=\"ObserverSetCharacterSpec1\",Keys=((Key=One),())),(ActionName=\"ObserverSetCharacterSpec2\",Keys=((Key=Two),())),(ActionName=\"ObserverSetCharacterSpec3\",Keys=((Key=Three),())),(ActionName=\"ObserverSetCharacterSpec4\",Keys=((Key=Four),())),(ActionName=\"ObserverSetCharacterSpec5\",Keys=((Key=Five),())),(ActionName=\"ObserverSetCharacterSpec6\",Keys=((Key=Six),())),(ActionName=\"ObserverSetCharacterSpec7\",Keys=((Key=Seven),())),(ActionName=\"ObserverSetCharacterSpec8\",Keys=((Key=Eight),())),(ActionName=\"ObserverSetCharacterSpec9\",Keys=((Key=Nine),())),(ActionName=\"ObserverSetCharacter0\",Keys=((Key=Zero,bAlt=True),())),(ActionName=\"ObserverSetCharacter1\",Keys=((Key=One,bAlt=True),())),(ActionName=\"ObserverSetCharacter2\",Keys=((Key=Two,bAlt=True),())),(ActionName=\"ObserverSetCharacter3\",Keys=((Key=Three,bAlt=True),())),(ActionName=\"ObserverSetCharacter4\",Keys=((Key=Four,bAlt=True),())),(ActionName=\"ObserverSetCharacter5\",Keys=((Key=Five,bAlt=True),())),(ActionName=\"ObserverSetCharacter6\",Keys=((Key=Six,bAlt=True),())),(ActionName=\"ObserverSetCharacter7\",Keys=((Key=Seven,bAlt=True),())),(ActionName=\"ObserverSetCharacter8\",Keys=((Key=Eight,bAlt=True),())),(ActionName=\"ObserverSetCharacter9\",Keys=((Key=Nine,bAlt=True),())),(ActionName=\"SwitchCameraSpectator\",Keys=((Key=LeftMouseButton),(Key=V))),(ActionName=\"SwitchCameraFollow\",Keys=((Key=RightMouseButton),(Key=C))),(ActionName=\"ObserverSetFree\",Keys=((Key=SpaceBar),(Key=F))),(ActionName=\"TogglePlayerList\",Keys=((Key=Tab),())),(ActionName=\"ToggleBattleList\",Keys=((Key=L),())),(ActionName=\"PlayerInfoDistanceUp\",Keys=((Key=RightBracket),())),(ActionName=\"PlayerInfoDistanceDown\",Keys=((Key=LeftBracket),())),(ActionName=\"ShowCarePackageItemList\",Keys=((Key=I),()))),AxisKeyList=((AxisName=\"FollowCamZoomIn\",Scale=1.000000,Keys=((Key=MouseWheelAxis),())),(AxisName=\"FollowCamZoomOut\",Scale=-1.000000,Keys=((Key=MouseWheelAxis),())),(AxisName=\"MoveForward\",Scale=1.000000,Keys=((Key=Z),())),(AxisName=\"MoveForward\",Scale=-1.000000,Keys=((Key=S),())),(AxisName=\"MoveRight\",Scale=1.000000,Keys=((Key=D),())),(AxisName=\"MoveRight\",Scale=-1.000000,Keys=((Key=Q),())),(AxisName=\"VehicleMoveForward\",Scale=1.000000,Keys=((Key=Z),(),(Key=Gamepad_LeftY))),(AxisName=\"VehicleMoveForward\",Scale=-1.000000,Keys=((Key=S),(),(Key=Gamepad_LeftTrigger))),(AxisName=\"VehicleMoveRight\",Scale=1.000000,Keys=((Key=D),(),(Key=Gamepad_LeftX))),(AxisName=\"VehicleMoveRight\",Scale=-1.000000,Keys=((Key=Q),())),(AxisName=\"AirControlPitch\",Scale=1.000000,Keys=((Key=SpaceBar),())),(AxisName=\"AirControlPitch\",Scale=-1.000000,Keys=((Key=LeftControl),())),(AxisName=\"AirControlRoll\",Scale=1.000000,Keys=((Key=E),())),(AxisName=\"AirControlRoll\",Scale=-1.000000,Keys=((Key=A),())),(AxisName=\"MoveUp\",Scale=1.000000,Keys=((Key=SpaceBar),(),(Key=Gamepad_LeftThumbstick))),(AxisName=\"MoveUp\",Scale=-1.000000,Keys=((Key=C),(),(Key=Gamepad_RightThumbstick))),(AxisName=\"FollowOrFreeCamZoomIn\",Scale=1.000000,Keys=((Key=MouseWheelAxis),())),(AxisName=\"FollowOrFreeCamZoomOut\",Scale=-1.000000,Keys=((Key=MouseWheelAxis),())),(AxisName=\"ObserverMoveUp\",Scale=1.000000,Keys=((Key=E),(),(Key=Gamepad_LeftThumbstick))),(AxisName=\"ObserverMoveUp\",Scale=-1.000000,Keys=((Key=Q),(),(Key=Gamepad_RightThumbstick))),(AxisName=\"FollowOrFreeCamZoomInit\",Scale=1.000000,Keys=(()))),MouseSensitiveList=((MouseSensitiveName=\"Normal\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"VehicleDriver\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Targeting\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Scoping\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Scope2X\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Scope4X\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Scope8X\",LastConvertedMouseSensitivity=0.020000),(MouseSensitiveName=\"Scope15X\",LastConvertedMouseSensitivity=0.020000)),bInvertMouse=False)";
    public static String source_formatted = "CustomInputSettins=(" +
        "ActionKeyList=(" + 
            "(ActionName=\"Walk\"," + 
            "Keys=(" + 
            	"(Key=<)," + 
            	"()))," +
            "(ActionName=\"Sprint\"," +
            "Keys=(" +
            	"(Key=LeftShift)," +
            	"()))," +
            "(ActionName=\"Jump\"," +
            "Keys=(" +
            	"(Key=SpaceBar)," +
            	"()," +
            	"(Key=Gamepad_FaceButton_Bottom)))," +
            "(ActionName=\"ToggleCrouch\"," +
            "Keys=(" +
            	"(Key=LeftControl)," +
            	"()))," +
            "(ActionName=\"ToggleProne\"," +
            "Keys=(" +
            	"(Key=C)," +
            	"()))," +
            "(ActionName=\"Interact\"," +
            "Keys=(" +
            	"(Key=F)," +
            	"()," +
            	"(Key=Gamepad_FaceButton_Left)))," +
            "(ActionName=\"ToggleCamera\"," +
            "Keys=(" +
            	"(Key=V)," +
            	"()))," +
            "(ActionName=\"ToggleAutoRun\"," +
            "Keys=(" +
            	"(Key=Equals)," +
            	"(Key=NumLock)))," +
            "(ActionName=\"HoldRotation\"," +
            "Keys=(" +
            	"(Key=LeftAlt)," +
            	"()))," +
            "(ActionName=\"Fire\"," +
            "Keys=(" +
            	"(Key=LeftMouseButton)," +
            	"()," +
            	"(Key=Gamepad_RightTrigger)))," +
            "(ActionName=\"Targeting\"," +
            "Keys=(" +
            	"(Key=RightMouseButton)," +
            	"()," +
            	"(Key=Gamepad_LeftTrigger)))," +
            "(ActionName=\"Reload\"," +
            "Keys=(" +
            	"(Key=R)," +
            	"()," +
            	"(Key=Gamepad_FaceButton_Top)))," +
            "(ActionName=\"NextWeapon\"," +
            "Keys=(" +
				"(Key=MouseScrollDown)," +
            	"()))," +
            "(ActionName=\"PrevWeapon\"," +
            "Keys=(" +
				"(Key=MouseScrollUp)," +
            	"()))," +
            "(ActionName=\"Weapon_1\"," +
            "Keys=(" +
				"(Key=Hyphen)," +
            	"()))," +
            "(ActionName=\"Weapon_2\"," +
            "Keys=(" +
				"(Key=E_AccentGrave)," +
            	"()))," +
            "(ActionName=\"Weapon_3\"," +
            "Keys=(" +
				"(Key=Underscore)," +
            	"()))," +
            "(ActionName=\"Weapon_4\"," +
            "Keys=(" +
				"(Key=C_Cedille)," +
            	"()))," +
            "(ActionName=\"Weapon_5\"," +
            "Keys=(" +
				"(Key=A_AccentGrave)," +
            	"()))," +
            "(ActionName=\"ToggleFiringMode\"," +
            "Keys=(" +
				"(Key=B)," +
            	"()))," +
            "(ActionName=\"IncreaseZeroing\"," +
            "Keys=(" +
				"(Key=ThumbMouseButton2)," +
            	"()))," +
            "(ActionName=\"DecreaseZeroing\"," +
            "Keys=(" +
				"(Key=ThumbMouseButton)," +
            	"()))," +
            "(ActionName=\"PeekLeft\"," +
            "Keys=(" +
				"(Key=A)," +
            	"()))," +
            "(ActionName=\"PeekRight\"," +
            "Keys=(" +
				"(Key=E)," +
            	"()))," +
            "(ActionName=\"Unarm\"," +
            "Keys=(" +
				"(Key=X)," +
            	"()))," +
            "(ActionName=\"HoldBreath\"," +
            "Keys=(" +
				"(Key=LeftShift)," +
            	"()," +
            	"(Key=Gamepad_LeftShoulder)))," +
            "(ActionName=\"UseGrenade\"," +
            "Keys=(" +
				"(Key=G)," +
            	"()))," +
            "(ActionName=\"UseFlashBang\"," +
            "Keys=(" +
				"(Key=K)," +
            	"()))," +
            "(ActionName=\"UseSmokeBomb\"," +
            "Keys=(" +
				"(Key=H)," +
            	"()))," +
            "(ActionName=\"UseMolotov\"," +
            "Keys=(" +
				"(Key=J)," +
            	"()))," +
            "(ActionName=\"ResetZeroing\"," +
            "Keys=(" +
				"(Key=MiddleMouseButton)," +
            	"()))," +
            "(ActionName=\"UseMedKit\"," +
            "Keys=(" +
				"(Key=Ampersand)," +
            	"()))," +
            "(ActionName=\"UseFirstAid\"," +
            "Keys=(" +
				"(Key=E_AccentAigu)," +
            	"()))," +
            "(ActionName=\"UseBandage\"," +
            "Keys=(" +
				"(Key=Quote)," +
            	"()))," +
            "(ActionName=\"UseBoostItem\"," +
            "Keys=(" +
				"(Key=Apostrophe)," +
            	"()))," +
            "(ActionName=\"UseHealItem\"," +
            "Keys=(" +
				"(Key=Hyphen)," +
            	"()))," +
            "(ActionName=\"UseAdrenaline\"," +
            "Keys=(()))," +
            "(ActionName=\"UsePainKiller\"," +
            "Keys=(()))," +
            "(ActionName=\"UseEnergyDrink\"," +
            "Keys=(" +
                "()))," +
            "(ActionName=\"ToVehicleSeat_1\"," +
            "Keys=(" +
				"(Key=NumPadOne)," +
            	"()))," +
            "(ActionName=\"ToVehicleSeat_2\"," +
            "Keys=(" +
				"(Key=NumPadTwo)," +
            	"()))," +
            "(ActionName=\"ToVehicleSeat_3\"," +
            "Keys=(" +
				"(Key=NumPadThree)," +
            	"()))," +
            "(ActionName=\"ToVehicleSeat_4\"," +
            "Keys=(" +
				"(Key=NumPadFour)," +
            	"()))," +
            "(ActionName=\"ToVehicleSeat_5\"," +
            "Keys=(" +
				"(Key=NumPadFive)," +
            	"()))," +
            "(ActionName=\"Handbrake\"," +
            "Keys=(" +
				"(Key=SpaceBar)," +
            	"()," +
            	"(Key=Gamepad_FaceButton_Right)))," +
            "(ActionName=\"VehicleBoost\"," +
            "Keys=(" +
				"(Key=LeftShift)," +
            	"()," +
            	"(Key=Gamepad_FaceButton_Bottom)))," +
            "(ActionName=\"Horn\"," +
            "Keys=(" +
				"(Key=LeftMouseButton)," +
            	"()," +
            	"(Key=Gamepad_LeftThumbstick)))," +
            "(ActionName=\"ToggleMap\"," +
            "Keys=(" +
				"(Key=Comma)," +
            	"()," +
            	"(Key=Gamepad_Special_Left)))," +
            "(ActionName=\"ToggleInventory\"," +
            "Keys=(" +
			    "(Key=I)," +
            	"(Key=Tab)))," +
            "(ActionName=\"ItemStackCountHandling\"," +
            "Keys=(" +
                "(Key=LeftShift)," +
            	"()))," +
            "(ActionName=\"ToggleUI\"," +
            "Keys=(" +
				"(Key=U," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"DeleteMyMarker\"," +
            "Keys=(" +
				"(Key=Delete)," +
            	"()))," +
            "(ActionName=\"ToggleOption\"," +
            "Keys=(" +
				"(Key=O)," +
            	"()))," +
            "(ActionName=\"SetMapMarkerAtCurrentPosition\"," +
            "Keys=(" +
				"(Key=Insert)," +
            	"()))," +
            "(ActionName=\"PushToTalk\"," +
            "Keys=(" +
				"(Key=T)," +
            	"()))," +
            "(ActionName=\"ToggleMuteVoiceChat\"," +
            "Keys=(" +
				"(Key=T," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ToggleMuteMasterVolume\"," +
            "Keys=(" +
				"(Key=M," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"SwitchVoiceChannel\"," +
            "Keys=(" +
				"(Key=Y," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"PreviousPlayer\"," +
            "Keys=(" +
				"(Key=End)," +
            	"()))," +
            "(ActionName=\"NextPlayer\"," +
            "Keys=(" +
				"(Key=Home)," +
            	"()))," +
            "(ActionName=\"ObserverFastMove\"," +
            "Keys=(" +
				"(Key=LeftShift)," +
            	"()))," +
            "(ActionName=\"ObserverSlowMove\"," +
            "Keys=(" +
				"(Key=LeftControl)," +
            	"()))," +
            "(ActionName=\"ToggleObseverTagWidget\"," +
            "Keys=(" +
				"(Key=H)," +
            	"()))," +
            "(ActionName=\"ToggleShowObseverTagWeapon\"," +
            "Keys=(" +
				"(Key=J)," +
            	"()))," +
            "(ActionName=\"ToggleX-Ray\"," +
            "Keys=(" +
				"(Key=X)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation0\"," +
            "Keys=(" +
				"(Key=F10," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation1\"," +
            "Keys=(" +
				"(Key=F1," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation2\"," +
            "Keys=(" +
				"(Key=F2," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation3\"," +
            "Keys=(" +
				"(Key=F3," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation4\"," +
            "Keys=(" +
				"(Key=F4," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation5\"," +
            "Keys=(" +
				"(Key=F5," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation6\"," +
            "Keys=(" +
				"(Key=F6," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation7\"," +
            "Keys=(" +
				"(Key=F7," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation8\"," +
            "Keys=(" +
				"(Key=F8," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveLocation9\"," +
            "Keys=(" +
				"(Key=F9," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation0\"," +
            "Keys=(" +
				"(Key=F10)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation1\"," +
            "Keys=(" +
				"(Key=F1)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation2\"," +
            "Keys=(" +
				"(Key=F2)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation3\"," +
            "Keys=(" +
				"(Key=F3)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation4\"," +
            "Keys=(" +
				"(Key=F4)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation5\"," +
            "Keys=(" +
				"(Key=F5)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation6\"," +
            "Keys=(" +
				"(Key=F6)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation7\"," +
            "Keys=(" +
				"(Key=F7)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation8\"," +
            "Keys=(" +
				"(Key=F8)," +
            	"()))," +
            "(ActionName=\"ObserverSetLocation9\"," +
            "Keys=(" +
				"(Key=F9)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter0\"," +
            "Keys=(" +
				"(Key=Zero," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter1\"," +
            "Keys=(" +
				"(Key=One," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter2\"," +
            "Keys=(" +
				"(Key=Two," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter3\"," +
            "Keys=(" +
				"(Key=Three," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter4\"," +
            "Keys=(" +
				"(Key=Four," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter5\"," +
            "Keys=(" +
				"(Key=Five," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter6\"," +
            "Keys=(" +
				"(Key=Six," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter7\"," +
            "Keys=(" +
				"(Key=Seven," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter8\"," +
            "Keys=(" +
				"(Key=Eight," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSaveCharacter9\"," +
            "Keys=(" +
				"(Key=Nine," +
            	"bCtrl=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec0\"," +
            "Keys=(" +
				"(Key=Zero)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec1\"," +
            "Keys=(" +
				"(Key=One)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec2\"," +
            "Keys=(" +
				"(Key=Two)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec3\"," +
            "Keys=(" +
				"(Key=Three)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec4\"," +
            "Keys=(" +
				"(Key=Four)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec5\"," +
            "Keys=(" +
				"(Key=Five)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec6\"," +
            "Keys=(" +
				"(Key=Six)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec7\"," +
            "Keys=(" +
				"(Key=Seven)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec8\"," +
            "Keys=(" +
				"(Key=Eight)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacterSpec9\"," +
            "Keys=(" +
				"(Key=Nine)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter0\"," +
            "Keys=(" +
				"(Key=Zero," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter1\"," +
            "Keys=(" +
				"(Key=One," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter2\"," +
            "Keys=(" +
				"(Key=Two," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter3\"," +
            "Keys=(" +
				"(Key=Three," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter4\"," +
            "Keys=(" +
				"(Key=Four," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter5\"," +
            "Keys=(" +
				"(Key=Five," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter6\"," +
            "Keys=(" +
				"(Key=Six," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter7\"," +
            "Keys=(" +
				"(Key=Seven," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter8\"," +
            "Keys=(" +
				"(Key=Eight," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"ObserverSetCharacter9\"," +
            "Keys=(" +
				"(Key=Nine," +
            	"bAlt=True)," +
            	"()))," +
            "(ActionName=\"SwitchCameraSpectator\"," +
            "Keys=(" +
				"(Key=LeftMouseButton)," +
            	"(Key=V)))," +
            "(ActionName=\"SwitchCameraFollow\"," +
            "Keys=(" +
				"(Key=RightMouseButton)," +
            	"(Key=C)))," +
            "(ActionName=\"ObserverSetFree\"," +
            "Keys=(" +
				"(Key=SpaceBar)," +
            	"(Key=F)))," +
            "(ActionName=\"TogglePlayerList\"," +
            "Keys=(" +
				"(Key=Tab)," +
            	"()))," +
            "(ActionName=\"ToggleBattleList\"," +
            "Keys=(" +
				"(Key=L)," +
            	"()))," +
            "(ActionName=\"PlayerInfoDistanceUp\"," +
            "Keys=(" +
				"(Key=RightBracket)," +
            	"()))," +
            "(ActionName=\"PlayerInfoDistanceDown\"," +
            "Keys=(" +
				"(Key=LeftBracket)," +
            	"()))," +
            "(ActionName=\"ShowCarePackageItemList\"," +
            "Keys=(" +
				"(Key=I)," +
            	"())))," +
        "AxisKeyList=(" +
            "(AxisName=\"FollowCamZoomIn\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=MouseWheelAxis)," +
                "()))," +
            "(AxisName=\"FollowCamZoomOut\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=MouseWheelAxis)," +
                "()))," +
            "(AxisName=\"MoveForward\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=Z)," +
                "()))," +
            "(AxisName=\"MoveForward\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=S)," +
                "()))," +
            "(AxisName=\"MoveRight\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=D)," +
                "()))," +
            "(AxisName=\"MoveRight\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=Q)," +
                "()))," +
            "(AxisName=\"VehicleMoveForward\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=Z)," +
                "()," +
                "(Key=Gamepad_LeftY)))," +
            "(AxisName=\"VehicleMoveForward\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=S)," +
                "()," +
                "(Key=Gamepad_LeftTrigger)))," +
            "(AxisName=\"VehicleMoveRight\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=D)," +
                "()," +
                "(Key=Gamepad_LeftX)))," +
            "(AxisName=\"VehicleMoveRight\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=Q)," +
                "()))," +
            "(AxisName=\"AirControlPitch\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=SpaceBar)," +
                "()))," +
            "(AxisName=\"AirControlPitch\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=LeftControl)," +
                "()))," +
            "(AxisName=\"AirControlRoll\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=E)," +
                "()))," +
            "(AxisName=\"AirControlRoll\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=A)," +
                "()))," +
            "(AxisName=\"MoveUp\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=SpaceBar)," +
                "()," +
                "(Key=Gamepad_LeftThumbstick)))," +
            "(AxisName=\"MoveUp\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=C)," +
                "()," +
                "(Key=Gamepad_RightThumbstick)))," +
            "(AxisName=\"FollowOrFreeCamZoomIn\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=MouseWheelAxis)," +
                "()))," +
            "(AxisName=\"FollowOrFreeCamZoomOut\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=MouseWheelAxis)," +
                "()))," +
            "(AxisName=\"ObserverMoveUp\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "(Key=E)," +
                "()," +
                "(Key=Gamepad_LeftThumbstick)))," +
            "(AxisName=\"ObserverMoveUp\"," +
            "Scale=-1.000000," +
            "Keys=(" +
                "(Key=Q)," +
                "()," +
                "(Key=Gamepad_RightThumbstick)))," +
            "(AxisName=\"FollowOrFreeCamZoomInit\"," +
            "Scale=1.000000," +
            "Keys=(" +
                "())))," +
        "MouseSensitiveList=(" +
            "(MouseSensitiveName=\"Normal\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"VehicleDriver\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Targeting\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Scoping\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Scope2X\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Scope4X\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Scope8X\"," +
            "LastConvertedMouseSensitivity=0.020000)," +
            "(MouseSensitiveName=\"Scope15X\"," +
            "LastConvertedMouseSensitivity=0.020000))," +
        "bInvertMouse=False)";
    
}
